# Generated by Django 2.2.17 on 2021-06-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='asktime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
